insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('André Santos',to_date('2000-05-21','YYYY.MM.DD'),'925478589','andres@iade.pt','Rua de Lisboa, Nº57 2ºDireito, 1000-001 Lisboa','andreiade', 'M', 32541255); 
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Bruna Sousa',to_date('2002-01-02','YYYY.MM.DD'),'965544324','brunas@iade.pt','Rua dos Açores, Nº50 1ºEsquerdo, 1001-002 Lisboa','brunaiade', 'F', 77553844);  
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Fábio Santos',to_date('2001-06-20','YYYY.MM.DD'),'912239954','fabios@iade.pt','Rua de Lisboa, Nº57 3ºDireito, 1000-001 Lisboa','fabioiade', 'M', 33452252);
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Beatriz Carreira',to_date('2000-03-21','YYYY.MM.DD'),'927712439','beatrizc@iade.pt','Rua Almirante Barroso, Nº20 8ºDireito, 1005-003 Lisboa','beatriziade', 'F', 77884434); 
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Diogo José',to_date('2002-11-02','YYYY.MM.DD'),'963733483','diogoj@iade.pt','Rua Agostinho Lourenço, Nº2 10ºEsquerdo, 1010-008 Lisboa','diogoiade', 'M', 43453295);
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Rodrigo Mendes',to_date('2001-12-01','YYYY.MM.DD'),'968889659','rodrigom@iade.pt','Rua do Comércio, Nº8 16ºEsquerdo, 1014-008 Lisboa','rodrigoiade', 'M', 43563245);
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Anabela Espanca',to_date('2000-09-28','YYYY.MM.DD'),'934432339','anabelae@iade.pt','Rua Ferreira Lapa, Nº1 10ºDireito, 1020-008 Lisboa','anabelaiade', 'F', 46332258);
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Mauricio Henriques',to_date('2001-12-09','YYYY.MM.DD'),'913665348','mauricioh@iade.pt','Rua da Junqueira, Nº9 14ºEsquerdo, 1013-010 Lisboa','mauricioiade', 'M', 48994217);
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Maria Mendonça',to_date('2002-10-06','YYYY.MM.DD'),'963443243','mariam@iade.pt','Rua General Morais Sarmento, Nº10 2ºDireito, 1011-004 Lisboa','mariaiade', 'F', 25627845);


insert into courses (cour_name, cour_url) values ('Engenharia Informática','https://drive.google.com/drive/folders/1LVFYLPQ2vGa3pbYnWEqgJ6zh3a5nnwPt?usp=sharing');
insert into courses (cour_name, cour_url) values ('Informática de Gestão','https://drive.google.com/drive/folders/13thB9Cw8RVjxbL7cMn2u7tUC2agVcZ7Y');
insert into courses (cour_name, cour_url) values ('Games Development','https://drive.google.com/drive/folders/1l3XA_6SMP3uLWc6XnEfjXgj_0MphR23h?usp=sharing');

insert into units (unit_name, unit_semester) values ('Análise Matemática I', 1);
insert into units (unit_name, unit_semester) values ('Álgebra Linear', 1);
insert into units (unit_name, unit_semester) values ('Sistemas Digitais', 1);
insert into units (unit_name, unit_semester) values ('Fundamentos da Programação', 1);
insert into units (unit_name, unit_semester) values ('Estruturação do Pensamento Lógico', 1);
insert into units (unit_name, unit_semester) values ('Metodologia de Investigação', 1);
insert into units (unit_name, unit_semester) values ('Análise Matemática II', 2);
insert into units (unit_name, unit_semester) values ('Física', 2);
insert into units (unit_name, unit_semester) values ('Programação e Algoritmos', 2);
insert into units (unit_name, unit_semester) values ('Arquitectura de Computadores', 2);
insert into units (unit_name, unit_semester) values ('Redes e Comunicação de Dados', 2);
insert into units (unit_name, unit_semester) values ('Matemática Discreta', 3);
insert into units (unit_name, unit_semester) values ('Bases de Dados', 3);
insert into units (unit_name, unit_semester) values ('Programação de Dispositivos Móveis', 3);
insert into units (unit_name, unit_semester) values ('Programação Orientada por Objetos', 3);
insert into units (unit_name, unit_semester) values ('Competências Comunicacionais', 3);
insert into units (unit_name, unit_semester) values ('Projeto de Desenvolvimento Móvel', 3);
insert into units (unit_name, unit_semester) values ('Estatística', 4);
insert into units (unit_name, unit_semester) values ('Algoritmos e Estruturas de Dados', 4);
insert into units (unit_name, unit_semester) values ('Programação Web', 4);
insert into units (unit_name, unit_semester) values ('Interfaces e Usabilidade', 4);
insert into units (unit_name, unit_semester) values ('Sistemas de Informação Geográficos', 4);
insert into units (unit_name, unit_semester) values ('Projeto de Desenvolvimento Web', 4);
insert into units (unit_name, unit_semester) values ('Segurança Informática', 5);
insert into units (unit_name, unit_semester) values ('Inteligência Artificial', 5);
insert into units (unit_name, unit_semester) values ('Sistemas Distribuídos', 5);
insert into units (unit_name, unit_semester) values ('Engenharia de Software', 5);
insert into units (unit_name, unit_semester) values ('Projeto de Desenvolvimento de Software', 5);
insert into units (unit_name, unit_semester) values ('Computação Física e IoT', 6);
insert into units (unit_name, unit_semester) values ('Sistemas Operativos', 6);
insert into units (unit_name, unit_semester) values ('Compiladores', 6);
insert into units (unit_name, unit_semester) values ('Project Factory', 6);
insert into units (unit_name, unit_semester) values ('Ética e Deontologia Profissional', 6);
insert into units (unit_name, unit_semester) values ('Empreendedorismo - Base Tecnológica', 6);

insert into units (unit_name, unit_semester) values ('Matemática', 1);
insert into units (unit_name, unit_semester) values ('Arquitetura de Sistemas de Informação', 1);
insert into units (unit_name, unit_semester) values ('Gestão Empresarial', 1);
insert into units (unit_name, unit_semester) values ('Ciência, Fontes e Métodos', 1);
insert into units (unit_name, unit_semester) values ('Matemática Discreta', 2);
insert into units (unit_name, unit_semester) values ('Investigação Operacional', 2);
insert into units (unit_name, unit_semester) values ('Bases de Dados', 2);
insert into units (unit_name, unit_semester) values ('Criatividade e Pensamento Crítico', 2);
insert into units (unit_name, unit_semester) values ('Competências Comunicacionais', 2);
insert into units (unit_name, unit_semester) values ('Programação Orientada a Objetos', 2);
insert into units (unit_name, unit_semester) values ('Estatística', 3);
insert into units (unit_name, unit_semester) values ('Algoritmos e Estrutura de Dados', 3);
insert into units (unit_name, unit_semester) values ('Análise de Sistemas', 3);
insert into units (unit_name, unit_semester) values ('Contabilidade', 3);
insert into units (unit_name, unit_semester) values ('Design de Interfaces Gráficas', 3);
insert into units (unit_name, unit_semester) values ('Desenvolvimento de Interfaces Web', 3);
insert into units (unit_name, unit_semester) values ('Cibersegurança', 4);
insert into units (unit_name, unit_semester) values ('Redes e Comunicação de Dados', 4);
insert into units (unit_name, unit_semester) values ('Gestão Financeira', 4);
insert into units (unit_name, unit_semester) values ('Administração e Gestão de Informação', 4);
insert into units (unit_name, unit_semester) values ('Gestão de Recursos Humanos', 5);
insert into units (unit_name, unit_semester) values ('Economia', 5);
insert into units (unit_name, unit_semester) values ('Business Intelligence', 5);
insert into units (unit_name, unit_semester) values ('Sistemas de Informação Geográficos', 5);
insert into units (unit_name, unit_semester) values ('Data Mining and Web Analytics', 5);
insert into units (unit_name, unit_semester) values ('Projeto de Visualização de Informação', 5);
insert into units (unit_name, unit_semester) values ('Marketing e Comunicação Digital', 6);
insert into units (unit_name, unit_semester) values ('Business Process Management', 6);
insert into units (unit_name, unit_semester) values ('Gestão de Projetos Informáticos', 6);
insert into units (unit_name, unit_semester) values ('Empreendedorismo - Base Tecnológica', 6);
insert into units (unit_name, unit_semester) values ('Ética e Deontologia Profissional/Voluntariado', 6);
insert into units (unit_name, unit_semester) values ('Projeto Final', 6);

insert into units (unit_name, unit_semester) values ('Math, Physics and Games I', 1);
insert into units (unit_name, unit_semester) values ('Programming Fundamentals', 1);
insert into units (unit_name, unit_semester) values ('Visual Art for Games', 1);
insert into units (unit_name, unit_semester) values ('Game Production', 1);
insert into units (unit_name, unit_semester) values ('Computational Systems for Games', 1);
insert into units (unit_name, unit_semester) values ('2D Project', 1);
insert into units (unit_name, unit_semester) values ('Communication Skills', 1);
insert into units (unit_name, unit_semester) values ('Game Design', 2);
insert into units (unit_name, unit_semester) values ('Web Programming', 2);
insert into units (unit_name, unit_semester) values ('Databases', 2);
insert into units (unit_name, unit_semester) values ('Web Project', 2);
insert into units (unit_name, unit_semester) values ('Ethics and Professional Deontology', 2);
insert into units (unit_name, unit_semester) values ('Math and Physics for Games II', 3);
insert into units (unit_name, unit_semester) values ('Mobile Programming', 3);
insert into units (unit_name, unit_semester) values ('Game Frameworks', 3);
insert into units (unit_name, unit_semester) values ('Data Structures', 3);
insert into units (unit_name, unit_semester) values ('Multiplatform Project', 3);
insert into units (unit_name, unit_semester) values ('Science, Sources and Methods', 3);
insert into units (unit_name, unit_semester) values ('Math, Physics and Games III', 4);
insert into units (unit_name, unit_semester) values ('Computer Graphics', 4);
insert into units (unit_name, unit_semester) values ('Artificial Intelligence', 4);
insert into units (unit_name, unit_semester) values ('Software Development Methodologies', 4);
insert into units (unit_name, unit_semester) values ('3D Project', 4);
insert into units (unit_name, unit_semester) values ('Creativity and Critical Thinking', 4);
insert into units (unit_name, unit_semester) values ('Emerging game technologies', 5);
insert into units (unit_name, unit_semester) values ('Distributed Programming', 5);
insert into units (unit_name, unit_semester) values ('Security for Games', 5);
insert into units (unit_name, unit_semester) values ('Advanced Techniquesin Game Programming', 5);
insert into units (unit_name, unit_semester) values ('Multiplayer Project', 5);
insert into units (unit_name, unit_semester) values ('Business Model for Games', 5);
insert into units (unit_name, unit_semester) values ('Usability and user experience', 6);
insert into units (unit_name, unit_semester) values ('Integration with Social Networks and Other Platforms', 6);
insert into units (unit_name, unit_semester) values ('Game Engine Development', 6);
insert into units (unit_name, unit_semester) values ('Final Project', 6); 

insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,1);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,2);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,3);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,4);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,5);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,6);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,7);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,8);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,9);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,10);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,11);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,12);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,13);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,14);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,15);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,16);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,17);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,18);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,19);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,20);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,21);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,22);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,23);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,24);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,25);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,26);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,27);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,28);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,29);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,30);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,31);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,32);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,33);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,34);

insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,35);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,36);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,37);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,38);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,39);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,40);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,41);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,42);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,43);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,44);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,45);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,46);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,47);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,48);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,49);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,50);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,51);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,52);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,53);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,54);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,55);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,56);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,57);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,58);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,59);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,60);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,61);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,62);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,63);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,64);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,65);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,66);

insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,67);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,68);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,69);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,70);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,71);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,72);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,73);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,74);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,75);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,76);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,77);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,78);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,79);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,80);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,81);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,82);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,83);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,84);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,85);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,86);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,87);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,88);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,89);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,90);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,91);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,92);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,93);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,94);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,95);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,96);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,97);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,98);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,99);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,100);

insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,4);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,5);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,20);

insert into classes (cla_name) values ('LEI01M01');
insert into classes (cla_name) values ('LEI02M01');
insert into classes (cla_name) values ('LEI03M01');
insert into classes (cla_name) values ('LIG01M01');
insert into classes (cla_name) values ('LIG02M01');
insert into classes (cla_name) values ('LIG03M01');
insert into classes (cla_name) values ('LGD01M01');
insert into classes (cla_name) values ('LGD02M01');
insert into classes (cla_name) values ('LGD03M01');

insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,1);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,2);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,3);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,4);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,5);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,6);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,7);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,8);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,9);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,10);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,11);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,12);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,13);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,14);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,15);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,16);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,17);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,18);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,19);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,20);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,21);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,22);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,23);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,24);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,25);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,26);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,27);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,28);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,29);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,30);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,31);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,32);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,33);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,34);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,101);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,102);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,35);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,36);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,37);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,38);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,39);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,40);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,41);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,42);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,43);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,44);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,103);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,45);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,46);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,47);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,48);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,49);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,50);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,51);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,52);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,53);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,54);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,55);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,56);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,57);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,58);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,59);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,60);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,61);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,62);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,63);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,64);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,65);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,66);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,67);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,68);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,69);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,70);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,71);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,72);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,73);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,74);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,75);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,76);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,77);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,78);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,79);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,80);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,81);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,82);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,83);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,84);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,85);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,86);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,87);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,88);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,89);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,90);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,91);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,92);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,93);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,94);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,95);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,96);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,97);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,98);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,99);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,100);

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,24,14,to_date('2019.09.28','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,25,12,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,26,11,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,27,10,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,28,18,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,29,15,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,30,09,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,31,12,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,32,15,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,33,17,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,34,18,to_date('2019.09.15','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,1,08,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,2,12,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,3,15,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,4,16,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,5,06,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,6,19,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,7,10,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,8,14,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,9,13,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,10,12,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,11,13,to_date('2021.09.25','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,12,13,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,13,11,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,14,18,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,15,05,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,16,13,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,17,18,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,18,12,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,19,11,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,20,10,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,21,16,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,22,13,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,23,11,to_date('2020.09.10','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,58,04,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,59,14,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,60,16,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,61,12,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,62,10,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,63,14,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,64,12,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,65,15,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,66,16,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,67,20,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,68,08,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,69,06,to_date('2019.09.18','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,35,16,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,36,16,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,37,10,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,38,12,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,39,08,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,40,06,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,41,10,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,42,11,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,43,12,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,44,13,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,45,15,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,46,16,to_date('2021.09.22','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,47,12,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,48,13,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,49,14,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,50,05,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,51,12,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,52,10,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,53,09,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,54,12,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,55,11,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,56,16,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,67,17,to_date('2020.09.10','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,94,16,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,95,12,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,96,13,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,97,10,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,98,11,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,99,09,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,100,16,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,101,13,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,102,14,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,103,18,to_date('2019.10.01','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,82,15,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,83,12,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,84,13,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,85,10,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,86,05,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,87,07,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,88,12,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,89,14,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,90,12,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,91,11,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,92,10,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,93,15,to_date('2020.09.30','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,70,15,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,71,14,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,72,10,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,73,11,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,74,09,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,75,08,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,76,11,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,77,12,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,78,10,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,79,15,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,80,17,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,81,16,to_date('2021.09.29','YYYY.MM.DD'));

insert into teachers (teach_name, teach_phone, teach_email) values ('Miguel Albertino','926632234','miguelta@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Ana Silva','935443311','anats@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('José Viana','915322589','josetv@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Mariana Castro','915883920','marianatc@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Ricardo Reis','935454589','ricardotr@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Alberto Caeiro','935543211','albertotc@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Bernardo Soares','919903123','bernardots@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Fernando Pessoa','928322147','fernandotp@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Sebastião Alves','914431242','sebastiaota@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Mateus Matos','927734139','luistc@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Maria Santos','911354542','mariats@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Luísa Mendes','934734613','luisatm@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Susana Martins','9211672234','susanatm@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Ulisses Esteves','932111896','ulisseste@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Carlos Almeida','924978563','carlosta@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Ana Francisca','916792341','anatf@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Isabel Martins','935177843','isabeltm@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Paulo Chaves','924417853','paulotc@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Joaquim Trovão','923985463','joaquimtt@iade.pt');
insert into teachers (teach_name, teach_phone, teach_email) values ('Joana Marques','914894321','joanatm@iade.pt');

insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (1,1);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (2,2);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (3,3);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (4,4);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (5,5);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (6,6);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (7,7);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (8,8);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (9,9);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (10,10);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (11,11);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (12,1);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (13,4);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (14,6);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (15,3);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (16,6);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (17,20);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (18,11);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (19,16);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (20,5);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (21,7);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (22,10);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (23,12);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (24,1);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (25,20);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (26,15);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (27,17);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (28,12);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (29,5);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (30,3);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (31,2);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (32,8);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (33,9);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (34,13);

insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (35,20);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (36,19);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (37,18);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (38,17);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (39,16);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (40,15);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (41,14);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (42,13);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (43,12);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (44,11);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (45,7);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (46,5);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (47,4);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (49,2);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (50,10);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (51,13);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (52,12);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (53,7);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (54,4);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (55,10);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (56,6);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (57,2);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (58,3);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (59,8);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (60,9);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (61,1);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (62,4);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (63,18);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (64,19);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (65,17);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (66,12);

insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (67,8);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (68,14);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (69,16);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (70,18);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (71,17);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (72,12);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (73,13);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (74,17);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (75,3);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (76,2);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (77,1);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (78,10);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (79,2);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (80,6);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (81,7);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (82,3);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (83,8);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (84,10);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (85,11);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (86,12);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (87,20);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (88,19);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (89,15);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (90,1);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (91,10);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (92,20);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (93,12);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (94,13);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (95,2);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (96,3);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (97,7);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (98,8);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (99,16);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (100,18);

insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (101,10);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (102,9);
insert into uniteachers (unitte_unitcour_id, unitte_teach_id) values (103,13);




insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Segunda', 6, 376322554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Terça', 2, 376322556);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','18:00:00', 'Terça', 1, 376322557);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quarta', 4, 376322558);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Quinta', 1, 376322559);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quinta', 3, 376322514);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','17:00:00', 'Sexta', 2, 376322534);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Sexta', 5, 376322574);

insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Segunda', 7, 376324554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Terça', 8, 376352554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','18:00:00', 'Terça', 7, 376329554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quarta', 10, 376122554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Quinta', 11, 376222554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quinta', 8, 376382554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','17:00:00', 'Sexta', 9, 376342554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Sexta', 10, 376482554);



insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Segunda', 17, 276322554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('10:00:00','12:00:00', 'Segunda', 15, 174322554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Terça', 16, 376482554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','11:00:00', 'Quarta', 14, 376562554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('11:00:00','14:00:00', 'Quarta', 12, 376442554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Quinta', 15, 376142554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('10:00:00','13:00:00', 'Quinta', 13, 376375554);

insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Segunda', 18, 376472554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('10:00:00','12:00:00', 'Segunda', 22, 376462554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Terça', 19, 376329954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','11:00:00', 'Quarta', 23, 376366554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('11:00:00','14:00:00', 'Quarta', 20, 376327354);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Quinta', 21, 376323954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Sexta', 23, 376328954);



insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Segunda', 24, 663225549);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Terça', 26, 376324214);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','18:00:00', 'Terça', 25, 376329994);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quarta', 28, 376375354);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Quinta', 27, 376315954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quinta', 24, 376345654);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','17:00:00', 'Sexta', 25, 376324584);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Sexta', 26, 376329524);

insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Segunda', 29, 376145554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('10:00:00','12:00:00', 'Segunda', 30, 376455554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Terça', 34, 376327854);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','11:00:00', 'Quarta', 31, 376312394);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('11:00:00','14:00:00', 'Quarta', 33, 376327794);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Quinta', 32, 376329954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Sexta', 29, 376392452);




insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Segunda', 35, 376145154);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('10:00:00','12:00:00', 'Segunda', 38, 376455551);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Terça', 36, 376327815);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','11:00:00', 'Quarta', 37, 376312394);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('11:00:00','14:00:00', 'Sexta', 39, 376317794);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Quinta', 36, 376319954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Sexta', 40, 376391452);

insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Segunda', 41, 306145154);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('10:00:00','12:00:00', 'Segunda', 42, 306455551);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Terça', 45, 306327815);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','11:00:00', 'Quarta', 44, 306312394);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('11:00:00','14:00:00', 'Sexta', 43, 306317794);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Quinta', 41, 306319954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Sexta', 46, 306391452);


insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Segunda', 47, 336145154);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('10:00:00','12:00:00', 'Terça', 49, 336455551);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Terça', 51, 336327815);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','11:00:00', 'Quarta', 50, 336312394);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('11:00:00','14:00:00', 'Sexta', 48, 336317794);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Quinta', 47, 336319954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Sexta', 52, 336391452);

insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Segunda', 53, 306147754);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('10:00:00','12:00:00', 'Segunda', 54, 306457751);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Terça', 55, 306327877);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','11:00:00', 'Quarta', 56, 306312774);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('11:00:00','14:00:00', 'Sexta', 54, 306317797);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Quinta', 53, 306377954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Sexta', 57, 306771452);


insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Segunda', 58, 336145154);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('10:00:00','12:00:00', 'Terça', 58, 336455551);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Terça', 60, 336327815);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','11:00:00', 'Quarta', 62, 336312394);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('11:00:00','14:00:00', 'Sexta', 59, 336317794);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Quinta', 61, 336319954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Sexta', 63, 336391452);

insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Segunda', 64, 306147754);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('10:00:00','12:00:00', 'Sexta', 68, 306457751);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Terça', 67, 306327877);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','11:00:00', 'Quarta', 65, 306312774);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('11:00:00','14:00:00', 'Sexta', 66, 306317797);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Quinta', 64, 306377954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('08:00:00','10:00:00', 'Sexta', 69, 306771452);




insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Segunda', 70, 376327854);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Terça', 72, 379922556);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','18:00:00', 'Terça', 71, 371922557);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quarta', 74, 479322558);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Quinta', 76, 987322559);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quinta', 73, 965322514);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','17:00:00', 'Sexta', 75, 399522534);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Sexta', 70, 396322574);

insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Segunda', 77, 986324554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Terça', 78, 379982554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','18:00:00', 'Terça', 80, 379999554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quarta', 79, 999922554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Quinta', 78, 376999954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quinta', 77, 376888854);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','17:00:00', 'Sexta', 80, 376377774);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Sexta', 81, 376422224);


insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Quinta', 82, 376332154);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Terça', 85, 379925326);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','18:00:00', 'Terça', 84, 371926534);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quarta', 86, 488492021);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Quinta', 81, 987390559);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('18:00:00','19:00:00', 'Segunda', 83, 965388514);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','17:00:00', 'Segunda', 82, 399528834);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Sexta', 87, 396328874);

insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Segunda', 88, 988214554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Terça', 91, 895023574);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','18:00:00', 'Terça', 89, 379092345);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quarta', 94, 894386345);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Quarta', 92, 309346321);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quinta', 89, 355648854);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','17:00:00', 'Segunda', 90, 366377774);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Sexta', 93, 376422123);



insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Quinta', 94, 370332154);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Quinta', 96, 379025326);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','18:00:00', 'Terça', 97, 371026534);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quarta', 96, 488492021);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Quinta', 95, 98090559);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('18:00:00','19:00:00', 'Segunda', 98, 960388514);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','17:00:00', 'Quarta', 94, 390528834);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Sexta', 99, 396308874);

insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Segunda', 100, 988219554);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Terça', 102, 895023594);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','18:00:00', 'Terça', 102, 379092395);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quarta', 101, 894386945);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('14:00:00','16:00:00', 'Quarta', 103, 309346921);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','19:00:00', 'Quinta', 101, 355648954);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('16:00:00','17:00:00', 'Segunda', 103, 366379774);
insert into schedules (sche_begin, sche_end, sche_weekday, sche_cps_id, sche_qr) values ('17:00:00','19:00:00', 'Sexta', 100, 376422193);





insert into resources (res_unitcour_id, res_url) values (1,'https://drive.google.com/drive/folders/1xF9FI6M63_ZT7We1X-dmnqbn3w6uVV_W');
insert into resources (res_unitcour_id, res_url) values (2,'https://drive.google.com/drive/folders/14BIkJ-f3EjxFNOFvoYEZCPcODXZjZl0d');
insert into resources (res_unitcour_id, res_url) values (3,'https://drive.google.com/drive/folders/1R_PlNOYOfrFhpOEPqoZ7-L8HFyuYI8Md');
insert into resources (res_unitcour_id, res_url) values (4,'https://drive.google.com/drive/folders/1uTTInh3apWyo9hqhOSCrPoDF_hdHiFGI');
insert into resources (res_unitcour_id, res_url) values (5,'https://drive.google.com/drive/folders/17nhyOsJX1SnEFjNSr3Ri7PYomMNEkkAe');
insert into resources (res_unitcour_id, res_url) values (6,'https://drive.google.com/drive/folders/1N87F5w7yYzFEQlC0ET_NbN15tYjuXlSz');
insert into resources (res_unitcour_id, res_url) values (7,'https://drive.google.com/drive/folders/15YD9h39DP95e8Vg_9EWdPPdhKdKM8O1H');
insert into resources (res_unitcour_id, res_url) values (8,'https://drive.google.com/drive/folders/1hxMxrlphDlYaliizNU5u5TTCNwdXksAM');
insert into resources (res_unitcour_id, res_url) values (9,'https://drive.google.com/drive/folders/1xCTQflqnvokfkdoeahLnUR6N_KhDGcLu');
insert into resources (res_unitcour_id, res_url) values (10,'https://drive.google.com/drive/folders/1VKxvDIdvHhYWAtaLQ2oKARbhcl1BLZzE');
insert into resources (res_unitcour_id, res_url) values (11,'https://drive.google.com/drive/folders/1xp--irlrlK5keh8iPMfs1vI0_2hIUYrD');
insert into resources (res_unitcour_id, res_url) values (12,'https://drive.google.com/drive/folders/1fgxrXlJHk4wb2N7Y6an55c_Qd5dwQOEN');
insert into resources (res_unitcour_id, res_url) values (13,'https://drive.google.com/drive/folders/1eGNsOu9TS416XVu0yGBAAHJsgp1nf3Q-');
insert into resources (res_unitcour_id, res_url) values (14,'https://drive.google.com/drive/folders/1Y9SDMVVicvcMwsMgE3CD0FBRrDIwO_xM');
insert into resources (res_unitcour_id, res_url) values (15,'https://drive.google.com/drive/folders/1iAtMCyYzUjOKDLNwajPTjfx9eoClIOJr');
insert into resources (res_unitcour_id, res_url) values (16,'https://drive.google.com/drive/folders/12_8FvbNuocyea7jGwPOt7ppruhdgENRr');
insert into resources (res_unitcour_id, res_url) values (17,'https://drive.google.com/drive/folders/1vuMHSsOT-fD_vNzVRtCKR9qfuuyDuPF7');
insert into resources (res_unitcour_id, res_url) values (18,'https://drive.google.com/drive/folders/1gfAtu6fdqL14ox6V1j4xbQV3uap-ioU8');
insert into resources (res_unitcour_id, res_url) values (19,'https://drive.google.com/drive/folders/15LV0btUc_bw3xEY-OZQ8WZovijTkK5GP');
insert into resources (res_unitcour_id, res_url) values (20,'https://drive.google.com/drive/folders/1HKzlETDjCZPP1QxJYYWkF_tpdbLEots9');
insert into resources (res_unitcour_id, res_url) values (21,'https://drive.google.com/drive/folders/1N5ah9bzzFPVU6IL4BU4WHQx1PpIahQzO');
insert into resources (res_unitcour_id, res_url) values (22,'https://drive.google.com/drive/folders/12YMKUG6MVIfTMzBwr4ZhT-0Q0VmCastg');
insert into resources (res_unitcour_id, res_url) values (23,'https://drive.google.com/drive/folders/1YL6VQ1IVGfUY3LNVb48lJ5ouMHvJ6KJT');
insert into resources (res_unitcour_id, res_url) values (24,'https://drive.google.com/drive/folders/1lc8Dj5h56-PeRUJ_zv95PhFqKpVjZiw8');
insert into resources (res_unitcour_id, res_url) values (25,'https://drive.google.com/drive/folders/11O2VIY6E8flAh0kn_gXmCWceMGJ__r-4');
insert into resources (res_unitcour_id, res_url) values (26,'https://drive.google.com/drive/folders/10MKvuyA_pN9wLBvBe7QP-Pt79GKpVJRw');
insert into resources (res_unitcour_id, res_url) values (27,'https://drive.google.com/drive/folders/1nHDxwQzkA0hK7HNaaZ-b3dWkWKVlDOLh');
insert into resources (res_unitcour_id, res_url) values (28,'https://drive.google.com/drive/folders/1MWCok2EiROdyLKn_LCh6Qts750yUJaDM');
insert into resources (res_unitcour_id, res_url) values (29,'https://drive.google.com/drive/folders/1Of3fmpwR-H3ni_5k7BRdod_a1cQpWZoC');
insert into resources (res_unitcour_id, res_url) values (30,'https://drive.google.com/drive/folders/1yczkiYq_ZKKUKTKZcBkEanphPzfQdpGp');
insert into resources (res_unitcour_id, res_url) values (31,'https://drive.google.com/drive/folders/1S0H-gS99m8H7SEskrbC23KZI3nnTDqsa');
insert into resources (res_unitcour_id, res_url) values (32,'https://drive.google.com/drive/folders/1W2hk0vBRHsi3gkmhjNTkt8cUQxvbrAq5');
insert into resources (res_unitcour_id, res_url) values (33,'https://drive.google.com/drive/folders/1I0g3NnPZ58wtb3cwp97xJs65J8uMpPJc');
insert into resources (res_unitcour_id, res_url) values (34,'https://drive.google.com/drive/folders/1e2LA1AKcOJVSF0Wrra1SwlxiOld6InD-');
insert into resources (res_unitcour_id, res_url) values (35,'https://drive.google.com/drive/folders/1vu2anlRrDOD8zMxDpCggNGkwHRP14EZ_');
insert into resources (res_unitcour_id, res_url) values (36,'https://drive.google.com/drive/folders/1ktGyBuJEs5yuSiDhRkUSikl0oDJvTSNN');
insert into resources (res_unitcour_id, res_url) values (37,'https://drive.google.com/drive/folders/1jFNt40KfWM7nlwkyq4G8-sFX_fhFPY7j');
insert into resources (res_unitcour_id, res_url) values (38,'https://drive.google.com/drive/folders/1b04VZginxt8FJX8Rsd5_tD8orKBt30k6');
insert into resources (res_unitcour_id, res_url) values (39,'https://drive.google.com/drive/folders/1KmOPkWVNv-M_vTC6zCaxJl461p3Y4UEx');
insert into resources (res_unitcour_id, res_url) values (40,'https://drive.google.com/drive/folders/1pRaC5gTvH4B5ZBlVxv9rjn4wynx2WUyj');
insert into resources (res_unitcour_id, res_url) values (41,'https://drive.google.com/drive/folders/1Zyw9yQ30NuP8B8ek7KtkpDUJLKbkOU94');
insert into resources (res_unitcour_id, res_url) values (42,'https://drive.google.com/drive/folders/1PkuF41c4jJ0yfv7YXwg904UgEYKi5Jno');
insert into resources (res_unitcour_id, res_url) values (43,'https://drive.google.com/drive/folders/1PgyOW1l-cAscI59eBf08eEf6TuIyzEp_');
insert into resources (res_unitcour_id, res_url) values (44,'https://drive.google.com/drive/folders/1nqXw73I6QYIEoMbWD7xU36pJaou3N0gb');
insert into resources (res_unitcour_id, res_url) values (45,'https://drive.google.com/drive/folders/1HpjB134I1YHd-v2acQ-wZEW91PXwbWZy');
insert into resources (res_unitcour_id, res_url) values (46,'https://drive.google.com/drive/folders/1tOOKKGa6SnnYiEYNnUan4A_PU_hIO3-5');
insert into resources (res_unitcour_id, res_url) values (47,'https://drive.google.com/drive/folders/1kbZx4YOXHNMB1TdGi3WnEguHq4PN0XXj');
insert into resources (res_unitcour_id, res_url) values (48,'https://drive.google.com/drive/folders/1unUU9E70MkrDTxwOxxFUvgg13exger7W');
insert into resources (res_unitcour_id, res_url) values (49,'https://drive.google.com/drive/folders/1l_FLN0u7j80xzexEMA881XIftS-Vy6I2');
insert into resources (res_unitcour_id, res_url) values (50,'https://drive.google.com/drive/folders/1az_dwxyPMP_cJN3h_NNAAXLjv4ySSth2');
insert into resources (res_unitcour_id, res_url) values (51,'https://drive.google.com/drive/folders/1Z0YDeOEYDPXLovf5oMq3HKoTguwcLWCl');
insert into resources (res_unitcour_id, res_url) values (52,'https://drive.google.com/drive/folders/1DU4gVV80OyiRSfMbH_j-YgEo22ruzV73');
insert into resources (res_unitcour_id, res_url) values (53,'https://drive.google.com/drive/folders/1ZYpHCx1Ocv3SQJ5f7bV0OajAyzVW2VIE');
insert into resources (res_unitcour_id, res_url) values (54,'https://drive.google.com/drive/folders/1xsONU1PqE_e92DdwZzf-_UtFSFdZ2Q2q');
insert into resources (res_unitcour_id, res_url) values (55,'https://drive.google.com/drive/folders/1m0earwFymjRzZ1qPe_7Q84o4ghFyHEJN');
insert into resources (res_unitcour_id, res_url) values (56,'https://drive.google.com/drive/folders/1mCLFT2a6Bl6N2uG3ALHwGa3Mxab5azQc');
insert into resources (res_unitcour_id, res_url) values (57,'https://drive.google.com/drive/folders/1N9p1Zo42KUCQCAwVFEE4NpD8hDwtkjpA');
insert into resources (res_unitcour_id, res_url) values (58,'https://drive.google.com/drive/folders/143Sq3wp7MELhZUno4WWo2qLGfQ3zAAMI');
insert into resources (res_unitcour_id, res_url) values (59,'https://drive.google.com/drive/folders/1G94dtsPFsirkvwwRfeM1-NxUmoyMgDqc');
insert into resources (res_unitcour_id, res_url) values (60,'https://drive.google.com/drive/folders/1Q8jOfDH8HfJhaOsuZDsMaBNL05BjKpj6');
insert into resources (res_unitcour_id, res_url) values (61,'https://drive.google.com/drive/folders/1ffqutNFf2CPwSXWhKmqD0MTdZ1m9rJVq');
insert into resources (res_unitcour_id, res_url) values (62,'https://drive.google.com/drive/folders/1lRJcC4SGGHOmz2aiftwkt-O3RtnA5lOQ');
insert into resources (res_unitcour_id, res_url) values (63,'https://drive.google.com/drive/folders/1UVsmbnKH3dZfUD_gac_T8Ma9KezqOhsD');
insert into resources (res_unitcour_id, res_url) values (64,'https://drive.google.com/drive/folders/19zpv6wW7k2CE--FtG78IkbLVDwLEygBG');
insert into resources (res_unitcour_id, res_url) values (65,'https://drive.google.com/drive/folders/1WGrWKAD9QsLnelKLVw0UbzpcUQpzuTrf');
insert into resources (res_unitcour_id, res_url) values (66,'https://drive.google.com/drive/folders/1w3Qn1VZLYOtb6SBeKwxQjeylcFJDrADX');
insert into resources (res_unitcour_id, res_url) values (67,'https://drive.google.com/drive/folders/13BWeHeKDzj06l1NTXtR3OJmRCDmHypW0');
insert into resources (res_unitcour_id, res_url) values (68,'https://drive.google.com/drive/folders/18EocskpdQkkOEkzvltprqDdTa353CIJb');
insert into resources (res_unitcour_id, res_url) values (69,'https://drive.google.com/drive/folders/1L_hNj7P0jxPsh8CBYrMeelaMV06lT-yK');
insert into resources (res_unitcour_id, res_url) values (70,'https://drive.google.com/drive/folders/1HxDXGfeH6ulEEozTCjmanL7ulpxbKL2a');
insert into resources (res_unitcour_id, res_url) values (71,'https://drive.google.com/drive/folders/1TqcENaxJmTplHeJh5jjrTGDB_0qS_Dti');
insert into resources (res_unitcour_id, res_url) values (72,'https://drive.google.com/drive/folders/1iZEBYziUhDZ3TUXNgccFKkFGD2QeCibj');
insert into resources (res_unitcour_id, res_url) values (73,'https://drive.google.com/drive/folders/1MwjhKwS38_-KTbU0ywmUct_-eRBjlSif');
insert into resources (res_unitcour_id, res_url) values (74,'https://drive.google.com/drive/folders/1QcoSTzNhy4a65Ox7BYCtSVAhPGy6JV4B');
insert into resources (res_unitcour_id, res_url) values (75,'https://drive.google.com/drive/folders/1biu50gXwzAR05to5PX88RtKfqxHX4hFR');
insert into resources (res_unitcour_id, res_url) values (76,'https://drive.google.com/drive/folders/1XoMdgTo_dBTae2YGvzGjXcrdrUQo3aKo');
insert into resources (res_unitcour_id, res_url) values (77,'https://drive.google.com/drive/folders/1j0Fgu9RydQXpczXhAZrBhIaFe05JL86K');
insert into resources (res_unitcour_id, res_url) values (78,'https://drive.google.com/drive/folders/1QyeWJfc6HX_S8mBaXeWE8ZRf_EjAqPbB');
insert into resources (res_unitcour_id, res_url) values (79,'https://drive.google.com/drive/folders/1iSvVI65PMRBcSRmmRZaeDwCpnVJgMjTR');
insert into resources (res_unitcour_id, res_url) values (80,'https://drive.google.com/drive/folders/1nHWkhAYCVXLsPDNATwA2lDhoaOYiEbzV');
insert into resources (res_unitcour_id, res_url) values (81,'https://drive.google.com/drive/folders/1gtBY5YFxFiE6_3XoWmFnynm2YWmwWGMt');
insert into resources (res_unitcour_id, res_url) values (82,'https://drive.google.com/drive/folders/19DMGpvnOPmRTPxtKb1lh1tWiO-VI8qN-');
insert into resources (res_unitcour_id, res_url) values (83,'https://drive.google.com/drive/folders/1daKba2PXDgEJDejA7faI7QX-M-D30UXH');
insert into resources (res_unitcour_id, res_url) values (84,'https://drive.google.com/drive/folders/1ne2CbaYOJiEaeQ-It41lMspsiYbrSQQ7');
insert into resources (res_unitcour_id, res_url) values (85,'https://drive.google.com/drive/folders/13I7_17ayimDLJCTzIA3HHkwDqhQkkUEr');
insert into resources (res_unitcour_id, res_url) values (86,'https://drive.google.com/drive/folders/1hYZW_g87_VPrBJDFuJj7ZX1-VPuRsCpr');
insert into resources (res_unitcour_id, res_url) values (87,'https://drive.google.com/drive/folders/1SWaxJfqy6WUCZ8e_PvnodzCkxC-3R5zx');
insert into resources (res_unitcour_id, res_url) values (88,'https://drive.google.com/drive/folders/1wuaeAz3_Ka3kxI_YR2lIvwabJVspbqJa');
insert into resources (res_unitcour_id, res_url) values (89,'https://drive.google.com/drive/folders/1TTZYKWwoJHm-zlZjIq13PfCMUG_ZfDjE');
insert into resources (res_unitcour_id, res_url) values (90,'https://drive.google.com/drive/folders/1_4iQRNwlpkQWdv02d2Fo0cBKbZI9cwLc');
insert into resources (res_unitcour_id, res_url) values (91,'https://drive.google.com/drive/folders/1udSi_i1v500baCUqxDSwjFfCi3pFiIP1');
insert into resources (res_unitcour_id, res_url) values (92,'https://drive.google.com/drive/folders/1Tlyk2N645F2LZU86E0ZrT0uxgT2_MFZJ');
insert into resources (res_unitcour_id, res_url) values (93,'https://drive.google.com/drive/folders/1eWhRZFOLevqWWoz7V85l_uQKLkChZbMF');
insert into resources (res_unitcour_id, res_url) values (94,'https://drive.google.com/drive/folders/1X4n2zlLuzemf5FZgDyE1q4eQahoCeOgN');
insert into resources (res_unitcour_id, res_url) values (95,'https://drive.google.com/drive/folders/1yPfjpAqSLdA5deWA1a3Ts_I1qfbF5eSj');
insert into resources (res_unitcour_id, res_url) values (96,'https://drive.google.com/drive/folders/1Okaz2b9XFuc8AN6XuZ_vckvVUvJhMYN_');
insert into resources (res_unitcour_id, res_url) values (97,'https://drive.google.com/drive/folders/1DKh_gaJovSScYikCSCcfjkXVYdsmN03S');
insert into resources (res_unitcour_id, res_url) values (98,'https://drive.google.com/drive/folders/1ZFjvBO7QrrEQKDh-LBquwHhpzVVIgo6b');
insert into resources (res_unitcour_id, res_url) values (99,'https://drive.google.com/drive/folders/1LkIVt94QG9x4Drl7QCo2bGDAxwnhRVXo');
insert into resources (res_unitcour_id, res_url) values (100,'https://drive.google.com/drive/folders/1m5gg5J7ZitaCjzyHamLtVe5zOycBabLq');
insert into resources (res_unitcour_id, res_url) values (101,'https://drive.google.com/drive/folders/1uTTInh3apWyo9hqhOSCrPoDF_hdHiFGI');
insert into resources (res_unitcour_id, res_url) values (102,'https://drive.google.com/drive/folders/17nhyOsJX1SnEFjNSr3Ri7PYomMNEkkAe');
insert into resources (res_unitcour_id, res_url) values (103,'https://drive.google.com/drive/folders/1HKzlETDjCZPP1QxJYYWkF_tpdbLEots9');

commit;








