insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('André Santos',to_date('2000-05-21','YYYY.MM.DD'),'925478589','andres@iade.pt','Rua de Lisboa, Nº57 2ºDireito, 1000-001 Lisboa','andreiade', 'M', 32541255); 
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Bruna Sousa',to_date('2002-01-02','YYYY.MM.DD'),'965544324','brunas@iade.pt','Rua dos Açores, Nº50 1ºEsquerdo, 1001-002 Lisboa','brunaiade', 'F', 77553844);  
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Fábio Santos',to_date('2001-06-20','YYYY.MM.DD'),'912239954','fabios@iade.pt','Rua de Lisboa, Nº57 3ºDireito, 1000-001 Lisboa','fabioiade', 'M', 33452252);
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Beatriz Carreira',to_date('2000-03-21','YYYY.MM.DD'),'927712439','beatrizc@iade.pt','Rua Almirante Barroso, Nº20 8ºDireito, 1005-003 Lisboa','beatriziade', 'F', 77884434); 
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Diogo José',to_date('2002-11-02','YYYY.MM.DD'),'963733483','diogoj@iade.pt','Rua Agostinho Lourenço, Nº2 10ºEsquerdo, 1010-008 Lisboa','diogoiade', 'M', 43453295);
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Rodrigo Mendes',to_date('2001-12-01','YYYY.MM.DD'),'968889659','rodrigom@iade.pt','Rua do Comércio, Nº8 16ºEsquerdo, 1014-008 Lisboa','rodrigoiade', 'M', 43563245);
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Anabela Espanca',to_date('2000-09-28','YYYY.MM.DD'),'934432339','anabelae@iade.pt','Rua Ferreira Lapa, Nº1 10ºDireito, 1020-008 Lisboa','anabelaiade', 'F', 46332258);
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Mauricio Henriques',to_date('2001-12-09','YYYY.MM.DD'),'913665348','mauricioh@iade.pt','Rua da Junqueira, Nº9 14ºEsquerdo, 1013-010 Lisboa','mauricioiade', 'M', 48994217);
insert into students (stu_name, stu_bdate, stu_phone, stu_email, stu_address, stu_password, stu_gender, stu_civilnum) values ('Maria Mendonça',to_date('2002-10-06','YYYY.MM.DD'),'963443243','mariam@iade.pt','Rua General Morais Sarmento, Nº10 2ºDireito, 1011-004 Lisboa','mariaiade', 'F', 25627845);


insert into courses (cour_name) values ('Engenharia Informática');
insert into courses (cour_name) values ('Informática de Gestão');
insert into courses (cour_name) values ('Games Development');

insert into units (unit_name, unit_semester) values ('Análise Matemática I', 1);
insert into units (unit_name, unit_semester) values ('Álgebra Linear', 1);
insert into units (unit_name, unit_semester) values ('Sistemas Digitais', 1);
insert into units (unit_name, unit_semester) values ('Fundamentos da Programação', 1);
insert into units (unit_name, unit_semester) values ('Estruturação do Pensamento Lógico', 1);
insert into units (unit_name, unit_semester) values ('Metodologia de Investigação', 1);
insert into units (unit_name, unit_semester) values ('Análise Matemática II', 2);
insert into units (unit_name, unit_semester) values ('Física', 2);
insert into units (unit_name, unit_semester) values ('Programação e Algoritmos', 2);
insert into units (unit_name, unit_semester) values ('Arquitectura de Computadores', 2);
insert into units (unit_name, unit_semester) values ('Redes e Comunicação de Dados', 2);
insert into units (unit_name, unit_semester) values ('Matemática Discreta', 3);
insert into units (unit_name, unit_semester) values ('Bases de Dados', 3);
insert into units (unit_name, unit_semester) values ('Programação de Dispositivos Móveis', 3);
insert into units (unit_name, unit_semester) values ('Programação Orientada por Objetos', 3);
insert into units (unit_name, unit_semester) values ('Competências Comunicacionais', 3);
insert into units (unit_name, unit_semester) values ('Projeto de Desenvolvimento Móvel', 3);
insert into units (unit_name, unit_semester) values ('Estatística', 4);
insert into units (unit_name, unit_semester) values ('Algoritmos e Estruturas de Dados', 4);
insert into units (unit_name, unit_semester) values ('Programação Web', 4);
insert into units (unit_name, unit_semester) values ('Interfaces e Usabilidade', 4);
insert into units (unit_name, unit_semester) values ('Sistemas de Informação Geográficos', 4);
insert into units (unit_name, unit_semester) values ('Projeto de Desenvolvimento Web', 4);
insert into units (unit_name, unit_semester) values ('Segurança Informática', 5);
insert into units (unit_name, unit_semester) values ('Inteligência Artificial', 5);
insert into units (unit_name, unit_semester) values ('Sistemas Distribuídos', 5);
insert into units (unit_name, unit_semester) values ('Engenharia de Software', 5);
insert into units (unit_name, unit_semester) values ('Projeto de Desenvolvimento de Software', 5);
insert into units (unit_name, unit_semester) values ('Computação Física e IoT', 6);
insert into units (unit_name, unit_semester) values ('Sistemas Operativos', 6);
insert into units (unit_name, unit_semester) values ('Compiladores', 6);
insert into units (unit_name, unit_semester) values ('Project Factory', 6);
insert into units (unit_name, unit_semester) values ('Ética e Deontologia Profissional', 6);
insert into units (unit_name, unit_semester) values ('Empreendedorismo - Base Tecnológica', 6);

insert into units (unit_name, unit_semester) values ('Matemática', 1);
insert into units (unit_name, unit_semester) values ('Arquitetura de Sistemas de Informação', 1);
insert into units (unit_name, unit_semester) values ('Gestão Empresarial', 1);
insert into units (unit_name, unit_semester) values ('Ciência, Fontes e Métodos', 1);
insert into units (unit_name, unit_semester) values ('Matemática Discreta', 2);
insert into units (unit_name, unit_semester) values ('Investigação Operacional', 2);
insert into units (unit_name, unit_semester) values ('Bases de Dados', 2);
insert into units (unit_name, unit_semester) values ('Criatividade e Pensamento Crítico', 2);
insert into units (unit_name, unit_semester) values ('Competências Comunicacionais', 2);
insert into units (unit_name, unit_semester) values ('Programação Orientada a Objetos', 2);
insert into units (unit_name, unit_semester) values ('Estatística', 3);
insert into units (unit_name, unit_semester) values ('Algoritmos e Estrutura de Dados', 3);
insert into units (unit_name, unit_semester) values ('Análise de Sistemas', 3);
insert into units (unit_name, unit_semester) values ('Contabilidade', 3);
insert into units (unit_name, unit_semester) values ('Design de Interfaces Gráficas', 3);
insert into units (unit_name, unit_semester) values ('Desenvolvimento de Interfaces Web', 3);
insert into units (unit_name, unit_semester) values ('Cibersegurança', 4);
insert into units (unit_name, unit_semester) values ('Redes e Comunicação de Dados', 4);
insert into units (unit_name, unit_semester) values ('Gestão Financeira', 4);
insert into units (unit_name, unit_semester) values ('Administração e Gestão de Informação', 4);
insert into units (unit_name, unit_semester) values ('Gestão de Recursos Humanos', 5);
insert into units (unit_name, unit_semester) values ('Economia', 5);
insert into units (unit_name, unit_semester) values ('Business Intelligence', 5);
insert into units (unit_name, unit_semester) values ('Sistemas de Informação Geográficos', 5);
insert into units (unit_name, unit_semester) values ('Data Mining and Web Analytics', 5);
insert into units (unit_name, unit_semester) values ('Projeto de Visualização de Informação', 5);
insert into units (unit_name, unit_semester) values ('Marketing e Comunicação Digital', 6);
insert into units (unit_name, unit_semester) values ('Business Process Management', 6);
insert into units (unit_name, unit_semester) values ('Gestão de Projetos Informáticos', 6);
insert into units (unit_name, unit_semester) values ('Empreendedorismo - Base Tecnológica', 6);
insert into units (unit_name, unit_semester) values ('Ética e Deontologia Profissional/Voluntariado', 6);
insert into units (unit_name, unit_semester) values ('Projeto Final', 6);

insert into units (unit_name, unit_semester) values ('Math, Physics and Games I', 1);
insert into units (unit_name, unit_semester) values ('Programming Fundamentals', 1);
insert into units (unit_name, unit_semester) values ('Visual Art for Games', 1);
insert into units (unit_name, unit_semester) values ('Game Production', 1);
insert into units (unit_name, unit_semester) values ('Computational Systems for Games', 1);
insert into units (unit_name, unit_semester) values ('2D Project', 1);
insert into units (unit_name, unit_semester) values ('Communication Skills', 1);
insert into units (unit_name, unit_semester) values ('Game Design', 2);
insert into units (unit_name, unit_semester) values ('Web Programming', 2);
insert into units (unit_name, unit_semester) values ('Databases', 2);
insert into units (unit_name, unit_semester) values ('Web Project', 2);
insert into units (unit_name, unit_semester) values ('Ethics and Professional Deontology', 2);
insert into units (unit_name, unit_semester) values ('Math and Physics for Games II', 3);
insert into units (unit_name, unit_semester) values ('Mobile Programming', 3);
insert into units (unit_name, unit_semester) values ('Game Frameworks', 3);
insert into units (unit_name, unit_semester) values ('Data Structures', 3);
insert into units (unit_name, unit_semester) values ('Multiplatform Project', 3);
insert into units (unit_name, unit_semester) values ('Science, Sources and Methods', 3);
insert into units (unit_name, unit_semester) values ('Math, Physics and Games III', 4);
insert into units (unit_name, unit_semester) values ('Computer Graphics', 4);
insert into units (unit_name, unit_semester) values ('Artificial Intelligence', 4);
insert into units (unit_name, unit_semester) values ('Software Development Methodologies', 4);
insert into units (unit_name, unit_semester) values ('3D Project', 4);
insert into units (unit_name, unit_semester) values ('Creativity and Critical Thinking', 4);
insert into units (unit_name, unit_semester) values ('Emerging game technologies', 5);
insert into units (unit_name, unit_semester) values ('Distributed Programming', 5);
insert into units (unit_name, unit_semester) values ('Security for Games', 5);
insert into units (unit_name, unit_semester) values ('Advanced Techniquesin Game Programming', 5);
insert into units (unit_name, unit_semester) values ('Multiplayer Project', 5);
insert into units (unit_name, unit_semester) values ('Business Model for Games', 5);
insert into units (unit_name, unit_semester) values ('Usability and user experience', 6);
insert into units (unit_name, unit_semester) values ('Integration with Social Networks and Other Platforms', 6);
insert into units (unit_name, unit_semester) values ('Game Engine Development', 6);
insert into units (unit_name, unit_semester) values ('Final Project', 6); 

insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,1);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,2);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,3);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,4);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,5);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,6);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,7);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,8);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,9);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,10);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,11);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,12);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,13);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,14);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,15);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,16);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,17);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,18);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,19);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,20);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,21);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,22);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,23);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,24);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,25);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,26);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,27);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,28);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,29);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,30);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,31);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,32);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,33);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (1,34);

insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,35);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,36);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,37);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,38);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,39);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,40);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,41);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,42);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,43);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,44);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,45);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,46);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,47);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,48);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,49);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,50);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,51);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,52);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,53);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,54);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,55);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,56);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,57);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,58);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,59);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,60);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,61);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,62);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,63);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,64);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,65);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (2,66);

insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,67);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,68);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,69);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,70);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,71);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,72);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,73);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,74);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,75);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,76);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,77);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,78);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,79);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,80);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,81);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,82);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,83);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,84);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,85);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,86);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,87);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,88);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,89);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,90);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,91);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,92);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,93);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,94);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,95);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,96);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,97);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,98);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,99);
insert into unitcourses (unitcour_cour_id, unitcour_unit_id) values (3,100);

insert into classes (cla_name) values ('LEI01M01');
insert into classes (cla_name) values ('LEI02M01');
insert into classes (cla_name) values ('LEI03M01');
insert into classes (cla_name) values ('LIG01M01');
insert into classes (cla_name) values ('LIG02M01');
insert into classes (cla_name) values ('LIG03M01');
insert into classes (cla_name) values ('LGD01M01');
insert into classes (cla_name) values ('LGD02M01');
insert into classes (cla_name) values ('LGD03M01');

insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,1);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,2);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,3);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,4);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,5);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,6);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,7);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,8);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,9);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,10);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (1,11);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,12);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,13);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,14);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,15);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,16);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,17);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,18);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,19);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,20);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,21);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,22);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (2,23);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,24);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,25);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,26);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,27);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,28);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,29);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,30);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,31);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,32);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,33);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (3,34);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,4);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,5);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,35);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,36);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,37);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,38);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,39);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,40);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,41);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,42);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,43);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (4,44);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,20);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,45);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,46);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,47);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,48);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,49);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,50);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,51);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,52);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,53);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (5,54);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,55);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,56);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,57);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,58);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,59);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,60);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,61);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,62);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,63);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,64);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,65);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (6,66);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,67);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,68);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,69);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,70);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,71);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,72);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,73);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,74);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,75);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,76);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,77);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (7,78);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,79);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,80);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,81);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,82);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,83);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,84);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,85);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,86);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,87);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,88);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,89);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,90);

insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,91);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,92);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,93);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,94);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,95);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,96);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,97);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,98);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,99);
insert into clapresches (cps_cla_id, cps_unitcour_id) values (8,100);

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,24,14,to_date('2019.09.28','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,25,12,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,26,11,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,27,10,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,28,18,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,29,15,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,30,09,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,31,12,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,32,15,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,33,17,to_date('2019.09.15','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (1,34,18,to_date('2019.09.15','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,1,08,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,2,12,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,3,15,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,4,16,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,5,06,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,6,19,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,7,10,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,8,14,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,9,13,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,10,12,to_date('2021.09.25','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (2,11,13,to_date('2021.09.25','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,12,13,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,13,11,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,14,18,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,15,05,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,16,13,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,17,18,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,18,12,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,19,11,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,20,10,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,21,16,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,22,13,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (3,23,11,to_date('2020.09.10','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,58,04,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,59,14,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,60,16,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,61,12,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,62,10,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,63,14,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,64,12,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,65,15,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,66,16,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,67,20,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,68,08,to_date('2019.09.18','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (4,69,06,to_date('2019.09.18','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,35,16,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,36,16,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,37,10,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,38,12,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,39,08,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,40,06,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,41,10,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,42,11,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,43,12,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,44,13,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,45,15,to_date('2021.09.22','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (5,46,16,to_date('2021.09.22','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,47,12,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,48,13,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,49,14,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,50,05,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,51,12,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,52,10,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,53,09,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,54,12,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,55,11,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,56,16,to_date('2020.09.10','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (6,67,17,to_date('2020.09.10','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,94,16,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,95,12,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,96,13,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,97,10,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,98,11,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,99,09,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,100,16,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,101,13,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,102,14,to_date('2019.10.01','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (7,103,18,to_date('2019.10.01','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,82,15,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,83,12,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,84,13,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,85,10,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,86,05,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,87,07,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,88,12,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,89,14,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,90,12,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,91,11,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,92,10,to_date('2020.09.30','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (8,93,15,to_date('2020.09.30','YYYY.MM.DD'));

insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,70,15,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,71,14,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,72,10,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,73,11,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,74,09,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,75,08,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,76,11,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,77,12,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,78,10,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,79,15,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,80,17,to_date('2021.09.29','YYYY.MM.DD'));
insert into enrollments (enroll_stu_id, enroll_cps_id, enroll_grade, enroll_date) values (9,81,16,to_date('2021.09.29','YYYY.MM.DD'));



commit;









